language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

script:
    - phpunit
    - ./vendor/bin/phpcs  -v --standard=tests/phpcs/ruleset.xml lib/

before_script: composer install --dev
